name: Wakatime Charts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMITTER_NAME: MinhOmega
          COMMITTER_EMAIL: minhvo050298@gmail.com
          AUTHOR_NAME: MinhOmega
          AUTHOR_EMAIL: minhvo050298@gmail.com
